# Generated by Django 5.1.3 on 2024-12-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_wallet_selected_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='name',
            field=models.CharField(default='Account1', max_length=100),
        ),
    ]
