# Generated by Django 5.1.3 on 2024-12-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_wallet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='name',
            field=models.CharField(default='Account-1', max_length=100),
        ),
    ]
