# Generated by Django 5.1.3 on 2024-11-29 17:10

import user_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_transactiondetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetails',
            name='transaction_id',
            field=models.CharField(default=user_management.models.generate_transaction_id, editable=False, max_length=10, unique=True),
        ),
    ]
