# Generated by Django 5.1.3 on 2024-12-12 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0008_tradingalgorithm_capital_requirement_and_more'),
        ('user_management', '0004_alter_wallet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='selected_trading_algorithm',
            field=models.ForeignKey(blank=True, help_text='The selected trading algorithm for this wallet.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallets', to='algo.tradingalgorithm'),
        ),
    ]
