# Generated by Django 5.1.3 on 2024-11-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_holdingstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdingstock',
            name='inversted_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10000000),
        ),
    ]
