# Generated by Django 5.1.3 on 2025-02-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_wallet_selected_trading_algorithm'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdingstock',
            name='stock_transaction_identity_code',
            field=models.CharField(default='null', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='stock_transaction_identity_code',
            field=models.CharField(default='null', max_length=30, null=True),
        ),
    ]
