# Generated by Django 5.1.3 on 2025-02-18 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_holdingstock_stock_transaction_identity_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holdingstock',
            name='stock_transaction_identity_code',
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='stock_transaction_identity_code',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='HoldingStockIdentityCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockTransaction_identity_code', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('HoldingStock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HoldingStockIdentityCode', to='user_management.holdingstock')),
            ],
        ),
    ]
