# Generated by Django 5.1.3 on 2024-12-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_holdingstock_inversted_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdingstock',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10000000),
        ),
    ]
