# Generated by Django 5.1.3 on 2024-12-01 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_holdingstock_current_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='InverstedAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inversted_amount', models.DecimalField(decimal_places=2, max_digits=10000000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_amount', models.DecimalField(decimal_places=2, max_digits=10000000)),
                ('Wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.wallet')),
            ],
        ),
    ]
