# Generated by Django 5.1.3 on 2025-02-18 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_remove_holdingstock_stock_transaction_identity_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inverstedamount',
            old_name='Wallet',
            new_name='wallet',
        ),
    ]
