# Generated by Django 5.1.3 on 2025-02-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0008_rename_wallet_inverstedamount_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdingstockidentitycode',
            name='created_at',
            field=models.DateTimeField(default=0.0009876543209876543),
        ),
    ]
