# Generated by Django 5.1.3 on 2024-12-04 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_stock_id'),
        ('user_management', '0008_inverstedamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetails',
            name='transaction_id',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.BigIntegerField(editable=False, unique=True)),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.stock')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StockTransaction', to='user_management.wallet')),
            ],
        ),
    ]
