# Generated by Django 5.1.3 on 2025-02-18 07:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_alter_holdingstockidentitycode_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdingstockidentitycode',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
