# Generated by Django 5.1.3 on 2025-02-18 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0014_alter_holdingstockidentitycode_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holdingstockidentitycode',
            name='created_at',
        ),
    ]
