# Generated by Django 5.1.3 on 2025-02-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0015_remove_holdingstockidentitycode_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdingstockidentitycode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
