# Generated by Django 5.1.3 on 2024-12-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdetails',
            name='opening_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
