# Generated by Django 5.1.3 on 2024-11-18 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdetails',
            name='stock',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='main.stock'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(default='null', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='yfinance_name',
            field=models.CharField(default='null', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='stockdetails',
            name='closing_price',
            field=models.CharField(default='null', max_length=10),
        ),
        migrations.AlterField(
            model_name='stockdetails',
            name='percentage_change',
            field=models.DecimalField(decimal_places=2, default='null', max_digits=5),
        ),
        migrations.AlterField(
            model_name='stockdetails',
            name='yfinance_name',
            field=models.CharField(default='null', max_length=50, unique=True),
        ),
    ]
