# Generated by Django 5.1.3 on 2024-12-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_stockdetails_opening_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdetails',
            name='high',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockdetails',
            name='low',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockdetails',
            name='opening_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
