# Generated by Django 5.1.3 on 2024-11-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_stockdetails_yfinance_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdetails',
            name='id',
            field=models.CharField(default=5, max_length=500, primary_key=True, serialize=False),
        ),
    ]
