# Generated by Django 5.1.3 on 2024-11-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_stockdetails_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
