# Generated by Django 5.1.3 on 2024-11-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_stockdetails_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdetails',
            name='closing_price',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=10),
        ),
    ]
