# Generated by Django 5.1.3 on 2024-11-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_stockdetails_closing_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdetails',
            name='closing_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
