# Generated by Django 5.1.3 on 2024-11-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_stockdetails_closing_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.CharField(default=3, max_length=200, primary_key=True, serialize=False),
        ),
    ]
