# Generated by Django 5.1.3 on 2024-11-18 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_stock_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdetails',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.stock'),
        ),
    ]
