# Generated by Django 5.1.3 on 2024-12-09 07:57

import algo.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '__first__'),
        ('user_management', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingAlgorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='algo_stocks', to='main.stock')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='algo_wallet', to='user_management.wallet')),
                ('trading_algorithm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trading_algorithm', to='algo.tradingalgorithm')),
            ],
        ),
        migrations.CreateModel(
            name='algo_performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WIN', 'Win'), ('LOSS', 'loss')], max_length=10)),
                ('profit_or_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('Trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='algo.trade')),
            ],
        ),
        migrations.CreateModel(
            name='StockSingleRsult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('NATURAL', 'Natural')], default='NATURAL', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single_result', to='main.stock')),
                ('tradingAlgorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradingAlgorithm_result', to='algo.tradingalgorithm')),
            ],
        ),
        migrations.CreateModel(
            name='TradingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.BigIntegerField(default=algo.models.generate_transaction_id_for_trading_transaction, editable=False, unique=True)),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=5)),
                ('trading_algorithm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='algo.tradingalgorithm')),
            ],
        ),
    ]
