# Generated by Django 5.1.3 on 2024-12-09 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0001_initial'),
        ('main', '__first__'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockSingleRsult',
            new_name='StocksignalResult',
        ),
    ]
