# Generated by Django 5.1.3 on 2024-12-09 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0002_rename_stocksinglersult_stocksignalresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StocksignalResult',
        ),
    ]
