# Generated by Django 5.1.3 on 2024-12-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0004_stocksignalresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksignalresult',
            name='stock_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
