# Generated by Django 5.1.3 on 2024-12-09 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0005_stocksignalresult_stock_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocksignalresult',
            name='stock_name',
        ),
    ]
