# Generated by Django 5.1.3 on 2024-12-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0006_remove_stocksignalresult_stock_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocksignalresult',
            name='signal',
            field=models.CharField(max_length=10),
        ),
    ]
