# Generated by Django 5.1.3 on 2024-12-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0007_alter_stocksignalresult_signal'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingalgorithm',
            name='capital_requirement',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tradingalgorithm',
            name='executes_on',
            field=models.CharField(default='All Trading Days', max_length=255),
        ),
        migrations.AddField(
            model_name='tradingalgorithm',
            name='function_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tradingalgorithm',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tradingalgorithm',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradingalgorithm',
            name='premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradingalgorithm',
            name='risk_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], default='Moderate', max_length=50),
        ),
        migrations.AddField(
            model_name='tradingalgorithm',
            name='subscription_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tradingalgorithm',
            name='trading_type',
            field=models.CharField(choices=[('Intraday', 'intraday'), ('Swing', 'swing'), ('Positional', 'positional'), ('longterm ', 'Longterm')], default='Swing', max_length=50),
        ),
    ]
