# Generated by Django 5.1.3 on 2024-12-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0008_tradingalgorithm_capital_requirement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocksignalresult',
            name='created_at',
            field=models.DateField(),
        ),
    ]
